// Package provision deploys the Cloudflare relay that Phaethon routes through.
//
// Provisioning sits behind an interface on purpose. Today the beta path shells
// out to Wrangler, which is quick and well documented; the destination is a
// direct Cloudflare API call using the user's own scoped token, so Wrangler
// and its Node dependency can be removed from onboarding without touching
// anything else here.
//
// Two rules hold for every implementation:
//
//   - Phaethon never carries Cloudflare credentials. Authorization belongs to
//     the user and to their own account.
//   - Every relay gets its own cryptographically random secret, generated
//     locally. A shared token would mean one tester's relay accepting
//     another's traffic.
package provision

import (
	"context"
	"fmt"
	"strings"

	"github.com/arahe-dev/phaethon/relay"
)

// Request describes the relay to provision.
type Request struct {
	// Project is the Cloudflare project name for the relay.
	Project string
	// Allowlist is the destination set the relay enforces for HTTP.
	Allowlist []string
	// TCPAllowlist is the host:port set the relay will carry raw TCP to. It is
	// applied as its own binding, so an HTTP entry can never imply a TCP one.
	TCPAllowlist []string
	// Token is the relay secret. It is generated by the caller and set as a
	// secret, never as a plain variable, so it does not appear in the
	// deployment's public configuration.
	Token string
	// Dir is a scratch directory the provider may use.
	Dir string
}

// Deployment is a provisioned relay.
type Deployment struct {
	// URL is the relay's base endpoint.
	URL string
	// Project identifies it in the user's Cloudflare account.
	Project string
	// Provider records how it was created, so a later migration knows what it
	// is dealing with.
	Provider string
}

// Provider deploys or adopts a relay.
type Provider interface {
	// Name identifies the implementation.
	Name() string
	// Describe explains, in one sentence, what the provider needs from the
	// user. It is shown before anything interactive happens.
	Describe() string
	// Available reports whether the provider's prerequisites are present,
	// with an actionable message when they are not.
	Available() error
	// Provision deploys a relay and returns its endpoint. It may be
	// interactive: a provider that needs authorization performs it here.
	Provision(ctx context.Context, req Request, logf func(string, ...any)) (Deployment, error)
}

// ExistingRelay adopts a relay the user already deployed.
//
// This exists so onboarding never hard-depends on Wrangler: a tester who has
// already deployed a relay, or who prefers to deploy it themselves, can supply
// it and continue. The endpoint is verified rather than trusted.
type ExistingRelay struct {
	// URL is the relay base endpoint.
	URL string
	// Token is the relay secret the user configured.
	Token string
	// HTTP performs the verification request. Injected so this package stays
	// testable without a network.
	HTTP HTTPDoer
}

// Name identifies the provider.
func (p *ExistingRelay) Name() string { return "existing" }

// Describe explains what the provider needs.
func (p *ExistingRelay) Describe() string {
	return "use a relay you have already deployed; Phaethon verifies it before adopting it"
}

// Available reports whether enough was supplied to verify the relay.
func (p *ExistingRelay) Available() error {
	if strings.TrimSpace(p.URL) == "" {
		return fmt.Errorf("no relay URL was supplied")
	}
	if strings.TrimSpace(p.Token) == "" {
		return fmt.Errorf("no relay token was supplied")
	}
	return nil
}

// Provision verifies an existing relay and adopts it.
func (p *ExistingRelay) Provision(ctx context.Context, req Request, logf func(string, ...any)) (Deployment, error) {
	if err := p.Available(); err != nil {
		return Deployment{}, err
	}
	url := strings.TrimRight(strings.TrimSpace(p.URL), "/")
	if !strings.HasPrefix(url, "https://") {
		return Deployment{}, fmt.Errorf("relay: the endpoint must be https (got %q)", url)
	}
	logf("verifying the relay at %s", url)
	if err := VerifyRelay(ctx, p.HTTP, url, p.Token, AllowlistProbe(req.Allowlist)); err != nil {
		return Deployment{}, err
	}
	return Deployment{URL: url, Project: req.Project, Provider: p.Name()}, nil
}

// AllowlistProbe picks a host from the allowlist that can safely be used to
// prove the relay fetches. It prefers a bare domain over a wildcard, and
// returns "" when nothing is suitable.
func AllowlistProbe(allowed []string) string {
	for _, p := range allowed {
		if p != "" && !strings.HasPrefix(p, "*.") && !strings.Contains(p, "*") {
			return p
		}
	}
	for _, p := range allowed {
		if strings.HasPrefix(p, "*.") {
			return strings.TrimPrefix(p, "*.")
		}
	}
	return ""
}

// defaultAllowlist is the destination set used when the caller supplied none.
// It fails closed: the relay refuses everything outside it.
func defaultAllowlist() []string {
	return relay.DefaultAllowlist()
}
